package org.example.laboratorinis.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import org.example.laboratorinis.mybatis.model.Extracurricular;

@Mapper
public interface ExtracurricularMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXTRACURRICULAR
     *
     * @mbg.generated Tue Apr 09 00:46:41 EEST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXTRACURRICULAR
     *
     * @mbg.generated Tue Apr 09 00:46:41 EEST 2024
     */
    int insert(Extracurricular record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXTRACURRICULAR
     *
     * @mbg.generated Tue Apr 09 00:46:41 EEST 2024
     */
    Extracurricular selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXTRACURRICULAR
     *
     * @mbg.generated Tue Apr 09 00:46:41 EEST 2024
     */
    List<Extracurricular> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXTRACURRICULAR
     *
     * @mbg.generated Tue Apr 09 00:46:41 EEST 2024
     */
    int updateByPrimaryKey(Extracurricular record);
}