package org.example.laboratorinis.mybatis.model;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE.ID
     *
     * @mbg.generated Tue Apr 09 00:46:41 EEST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE.KURSAS
     *
     * @mbg.generated Tue Apr 09 00:46:41 EEST 2024
     */
    private Integer kursas;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE.SPECIALTY
     *
     * @mbg.generated Tue Apr 09 00:46:41 EEST 2024
     */
    private String specialty;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE.ID
     *
     * @return the value of PUBLIC.COURSE.ID
     *
     * @mbg.generated Tue Apr 09 00:46:41 EEST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE.ID
     *
     * @param id the value for PUBLIC.COURSE.ID
     *
     * @mbg.generated Tue Apr 09 00:46:41 EEST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE.KURSAS
     *
     * @return the value of PUBLIC.COURSE.KURSAS
     *
     * @mbg.generated Tue Apr 09 00:46:41 EEST 2024
     */
    public Integer getKursas() {
        return kursas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE.KURSAS
     *
     * @param kursas the value for PUBLIC.COURSE.KURSAS
     *
     * @mbg.generated Tue Apr 09 00:46:41 EEST 2024
     */
    public void setKursas(Integer kursas) {
        this.kursas = kursas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE.SPECIALTY
     *
     * @return the value of PUBLIC.COURSE.SPECIALTY
     *
     * @mbg.generated Tue Apr 09 00:46:41 EEST 2024
     */
    public String getSpecialty() {
        return specialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE.SPECIALTY
     *
     * @param specialty the value for PUBLIC.COURSE.SPECIALTY
     *
     * @mbg.generated Tue Apr 09 00:46:41 EEST 2024
     */
    public void setSpecialty(String specialty) {
        this.specialty = specialty;
    }
}