package org.example.laboratorinis.mybatis.model;

import java.util.List;

public class Extracurricular {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EXTRACURRICULAR.ID
     *
     * @mbg.generated Wed Apr 10 13:15:35 EEST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EXTRACURRICULAR.NAME
     *
     * @mbg.generated Wed Apr 10 13:15:35 EEST 2024
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EXTRACURRICULAR.ID
     *
     * @return the value of PUBLIC.EXTRACURRICULAR.ID
     *
     * @mbg.generated Wed Apr 10 13:15:35 EEST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EXTRACURRICULAR.ID
     *
     * @param id the value for PUBLIC.EXTRACURRICULAR.ID
     *
     * @mbg.generated Wed Apr 10 13:15:35 EEST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EXTRACURRICULAR.NAME
     *
     * @return the value of PUBLIC.EXTRACURRICULAR.NAME
     *
     * @mbg.generated Wed Apr 10 13:15:35 EEST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EXTRACURRICULAR.NAME
     *
     * @param name the value for PUBLIC.EXTRACURRICULAR.NAME
     *
     * @mbg.generated Wed Apr 10 13:15:35 EEST 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    //additionally setting many to many relationship
    private List<Student> students;

    public void setStudents(List<Student> students) {
        this.students = students;
    }

    public void addStudent(Student student) {
        this.students.add(student);
    }

    public List<Student> getStudents() {
        return students;
    }
}