package org.example.laboratorinis.mybatis.model;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.ID
     *
     * @mbg.generated Tue Apr 09 00:46:41 EEST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.PAVARDE
     *
     * @mbg.generated Tue Apr 09 00:46:41 EEST 2024
     */
    private String pavarde;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.VARDAS
     *
     * @mbg.generated Tue Apr 09 00:46:41 EEST 2024
     */
    private String vardas;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.GRUPE_ID
     *
     * @mbg.generated Tue Apr 09 00:46:41 EEST 2024
     */
    private Integer grupeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.ID
     *
     * @return the value of PUBLIC.STUDENT.ID
     *
     * @mbg.generated Tue Apr 09 00:46:41 EEST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.ID
     *
     * @param id the value for PUBLIC.STUDENT.ID
     *
     * @mbg.generated Tue Apr 09 00:46:41 EEST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.PAVARDE
     *
     * @return the value of PUBLIC.STUDENT.PAVARDE
     *
     * @mbg.generated Tue Apr 09 00:46:41 EEST 2024
     */
    public String getPavarde() {
        return pavarde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.PAVARDE
     *
     * @param pavarde the value for PUBLIC.STUDENT.PAVARDE
     *
     * @mbg.generated Tue Apr 09 00:46:41 EEST 2024
     */
    public void setPavarde(String pavarde) {
        this.pavarde = pavarde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.VARDAS
     *
     * @return the value of PUBLIC.STUDENT.VARDAS
     *
     * @mbg.generated Tue Apr 09 00:46:41 EEST 2024
     */
    public String getVardas() {
        return vardas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.VARDAS
     *
     * @param vardas the value for PUBLIC.STUDENT.VARDAS
     *
     * @mbg.generated Tue Apr 09 00:46:41 EEST 2024
     */
    public void setVardas(String vardas) {
        this.vardas = vardas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.GRUPE_ID
     *
     * @return the value of PUBLIC.STUDENT.GRUPE_ID
     *
     * @mbg.generated Tue Apr 09 00:46:41 EEST 2024
     */
    public Integer getGrupeId() {
        return grupeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.GRUPE_ID
     *
     * @param grupeId the value for PUBLIC.STUDENT.GRUPE_ID
     *
     * @mbg.generated Tue Apr 09 00:46:41 EEST 2024
     */
    public void setGrupeId(Integer grupeId) {
        this.grupeId = grupeId;
    }
}